default_language_version:
    python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    # reject commits to master right away
      - id: no-commit-to-branch
        args: [--branch, master]
    # check for sensitive info and large files
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
    # simple file checks
      - id: check-yaml
      - id: check-json
        exclude: ^.devcontainer/
      - id: check-ast
    # python checks
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict

  # remove unnecessary imports
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3 # Possible releases: https://github.com/hadialqattan/pycln/tags
    hooks:
      - id: pycln
        language_version: python311
