default_language_version:
    python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    # reject commits to master right away
      - id: no-commit-to-branch
        args: [--branch, master]
    # simple file checks
      - id: check-yaml
      - id: check-json
      - id: check-ast
    # python checks
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-docstring-first

  # remove unnecessary imports
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3 # Possible releases: https://github.com/hadialqattan/pycln/tags
    hooks:
      - id: pycln
        language_version: python311
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1  # https://github.com/python/mypy/tags
    hooks:
      - id: mypy
        args: [--allow-subclassing-any]
        additional_dependencies: ['types-python-dateutil', 'types-requests']
        exclude: st_app
